### PR TITLE
Use slack_bolt instead of old implementation and remove unused code

### PR DESCRIPTION
**Pull request by matiascc**
* Use slack_bolt instead of old implementation
* Remove unused code associated to accounts folder/app
* Add changelog and justfile
* Add pre-commit hook and apply it to the code
* Update some libraries and remove unused ones
* Use envkey in local (the same as we were doing on prod), to make local setup easier

### CODE REVIEW

**Comment by weallwegot** [comment]
do we want to remove all the get_id by channel name and instead just use the Channel ID directly? or use it as a constant somewhere? that way it can be a bit more flexible / robust

**Comment by weallwegot** [comment]
and to my earlier comment about migrating this to a microservice. i think eventually but its a lot of work in this case it seems. 
the database piece in particular would be interesting. maybe even sqlite who knows... will add a story to backlog for that low priority

**Comment by weallwegot** [comment]
<https://linear.app/careervillage/issue/CV-884/move-qanda-slack-moderation-from-a-django-app-to-a-microservice>

**Comment by weallwegot** [comment]
@matiascc do you want this reviewed more by me or is it part of the ongoing work for pre-approval? ui cant really remember

**Comment by matiascc** [comment]
It is part of the pre-approval work. I'm doing the other changes on top of this ones.
Idk if we want to merge this one separately or only merge the pre-approval one, when it's ready

**Pull request merged**
